apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: python-ncbziyvl 
  janus-idp.io/tekton: python-ncbziyvl
  backstage.io/kubernetes-id: python-ncbziyvl
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: python-ncbziyvl
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml